export const PROJECT_DATA = [
  {
    id: 1,
    class: "팀 프로젝트",
    image: "",
    link: "",
    member: ["NextArchive", "박진수"],
    number: 2,
    outline: "미디어 유통 사이트 제작",
    part: [
      "서버 데이터 관리",
      "웹 FRONT_END 총괄 프로그래밍",
      "웹 BACK_END 총괄 프로그래밍",
    ],
    share: "50%",
    title: "NextArchive",
    tool: ["NextJS", "Tailwind", "TypeScript", "Redux"],
  },  {
    id: 2,
    class: "개인 프로젝트",
    image: "",
    link: "",
    member: ["박진수"],
    number: 1,
    outline: "Portfolio 사이트 제작",
    part: [
        "디자인 및 설계 제작"
    ],
    share: "100%",
    title: "Portfolio",
    tool: ["ReactJs", "Tailwind", "TypeScript", "Redux"],
  },  {
    id: 3,
    class: "팀 프로젝트",
    image: "",
    link: "",
    member: ["박진수", "전성태", "정예원", "강민구"],
    number: 4,
    outline: "고궁 축제 소개 사이트 제작",
    part: [
      "팀장",
      "작업 환경 구성",
      "팀원 자문",
      "코드 리모델링",
      "3D 모델링 및 3D 그래픽 구현",
    ],
    share: "50%",
    title: "밤을 걷다",
    tool: ["ReactJs", "Sass", "JavaScript", "ThreeJs"],
  }, {
    id: 4,
    class: "팀 프로젝트",
    image: "",
    link: "",
    member: ["민규리", "박진수", "강민구", "김정은"],
    number: 4,
    outline: "초등수학 문제집 사이트 제작",
    part: [
      "작업 환경 구성",
      "로그인 데이터 전달 작업",
      "플로우 차트 작성",
      "3D 모델링 및 3D 그래픽 구현",
    ],
    share: "30%",
    title: "독:수리",
    tool: ["ReactJs", "CSS3", "JavaScript", "ThreeJs"],
  },
];
